# Generated by Django 4.2.4 on 2023-08-31 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casas', '0002_casa_altura_casa_horario_casa_piso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje', models.PositiveSmallIntegerField()),
                ('comentario', models.CharField(max_length=150)),
            ],
        ),
        migrations.DeleteModel(
            name='Anfitrion',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.AddField(
            model_name='casa',
            name='anfitrion',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='casa',
            name='menu',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
